corpstats/urls.py
from django.conf.urls import url

from . import views

app_name = 'corpstat'

urlpatterns = [
    url(r'^$', views.corpstat_view, name='view'),
    url(r'^add/$', views.corpstats_add, name='add'),
    #url(r'^alliance/(?P<alliance_id>(\d)+)/$', views.alliance_view, name='view_alliance'),
    url(r'^overview/$', views.overview_view, name='view_all'),
    url(r'^(?P<corp_id>(\d)*)/$', views.corpstat_view, name='view_corp'),
    url(r'^(?P<corp_id>(\d)+)/update/$', views.corpstats_update, name='update'),
    url(r'^(?P<corp_id>(\d)+)/export/$', views.export_corpstats, name='export'), # has no permissions
    url(r'^search/$', views.corpstats_search, name='search'),
    ]

corpstats/models.py
import logging
import os
import json 
from django.core.serializers.json import DjangoJSONEncoder

from allianceauth.authentication.models import CharacterOwnership, UserProfile
from bravado.exception import HTTPForbidden
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from jsonschema.exceptions import ValidationError
from django.core.cache import cache
from django.utils import timezone

from esi.errors import TokenError
from esi.models import Token
from allianceauth.eveonline.models import EveCorporationInfo, EveCharacter
from allianceauth.notifications import notify

from allianceauth.services.hooks import ServicesHook
from allianceauth.eveonline.evelinks import eveimageserver
from .managers import CorpStatManager

from .provider import esi

logger = logging.getLogger(__name__)


SERVICE_DB = {
    "mumble":"mumble",
    "smf":"smf",
    "discord":"discord",
    "discorse":"discourse",
    "Wiki JS":"wikijs",
    "ips4":"ips4",
    "openfire":"openfire",
    "phpbb3":"phpbb3",
    "teamspeak3":"teamspeak3",
}

class CorpStat(models.Model):
    token = models.ForeignKey(Token, on_delete=models.CASCADE)
    corp = models.OneToOneField(EveCorporationInfo, on_delete=models.CASCADE)
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = (
            ('view_corp_corpstats', 'Can view corp stats of their corporation.'),
            ('view_alliance_corpstats', 'Can view corp stats of members of their alliance.'),
            ('view_state_corpstats', 'Can view corp stats of members of their auth state.'),
            ('view_all_corpstats', 'Can view all corp stats.'),
        )
        verbose_name = "corp stats"
        verbose_name_plural = "corp stats"

    objects = CorpStatManager()

    def __str__(self):
        return "%s for %s" % (self.__class__.__name__, self.corp)

    def update(self):
        try:
            # make sure the token owner is still in this corp
            corp_id = esi.client.Character.get_characters_character_id( 
                character_id=self.token.character_id).result()['corporation_id']
            assert corp_id == int(self.corp.corporation_id)

            # get member tracking data and retrieve member ids for translation
            tracking = esi.client.Corporation.get_corporations_corporation_id_membertracking(
                corporation_id=self.corp.corporation_id,
                token=self.token.valid_access_token()).result()
            member_ids = [t['character_id'] for t in tracking]

            # requesting too many ids per call results in a HTTP400
            # the swagger spec doesn't have a maxItems count
            # manual testing says we can do over 350, but let's not risk it
            member_id_chunks = [member_ids[i:i + 255] for i in range(0, len(member_ids), 255)]
            member_name_chunks = [esi.client.Universe.post_universe_names(ids=id_chunk).result() for id_chunk in
                                  member_id_chunks]

            member_list = {t['character_id']: t for t in tracking}
            for name_chunk in member_name_chunks:
                for name in name_chunk:
                    member_list[name['id']]['character_name'] = name.get('name', "")

            # get ship and location names  
            # TODO make this fast!
            for t in tracking:
                t['ship_type_name'] = ""
                if 'ship_type_id' in t: # non req'd esi model
                    if t['ship_type_id'] is not None:
                        try:
                            t['ship_type_name'] = esi.client.Universe.get_universe_types_type_id(type_id=t['ship_type_id']).result()['name'] #TODO use the inbuilt eve provider
                        except ValidationError as e:
                            logger.error(e)
                            pass  # Bad id or crappy esi call...

                #locations = c.Universe.post_universe_names(ids=[t['location_id']]).result()
                #t['location_name'] = locations[0]['name'] if locations else ''  # might be a citadel we can't know about

                member_list[t['character_id']].update(t)

            # purge old members
            old_members = CorpMember.objects.filter(corpstats=self)
            if old_members.exists():
                old_members._raw_delete(old_members.db)

            member_db_create = []
            # bulk update and create new member models
            for c_id, data in member_list.items():
                member_db_create.append(CorpMember(corpstats=self, **data))

            CorpMember.objects.bulk_create(member_db_create)
            # update the timer
            self.save()

        except TokenError as e:
            logger.warning("%s failed to update: %s" % (self, e))
            if self.token.user:
                notify(self.token.user, "%s failed to update with your ESI token." % self,
                       message="Your token has expired or is no longer valid. Please add a new one to create a new CorpStats.",
                       level="error")
            self.delete()
        except HTTPForbidden as e:
            logger.warning("%s failed to update: %s" % (self, e))
            if self.token.user:
                notify(self.token.user, "%s failed to update with your ESI token." % self,
                       message="%s: %s" % (e.status_code, e.message), level="error")
            self.delete()
        except AssertionError as e:
            logger.warning("%s token character no longer in corp." % self)
            if self.token.user:
                notify(self.token.user, "%s cannot update with your ESI token." % self,
                       message="%s cannot update with your ESI token as you have left corp." % self, level="error")
            self.delete()

    def build_cache_key(self):
        return f"CORPSTAT_{self.corp_id}"
    
    def get_cached_overview(self):
        data = cache.get(self.build_cache_key, False)
        if data:
            return json.loads(data)
        else:
            return self.get_and_cache_stats(only_context=True)

    def get_and_cache_stats(self, only_context=False):
        members, mains, orphans, unregistered, total_mains, total_unreg, total_members, auth_percent, alt_ratio, service_percent, tracking, services = self.get_stats()
        context = {
                "corp_name":self.corp.corporation_name,
                "total_mains":total_mains,
                "total_members":total_members,
                "authd_members":len(members),
                "auth_percent":auth_percent,
                "service_percent":service_percent,
                "alt_ratio":alt_ratio,
                "orphan_count":len(orphans)
        }
        cache.set(self.build_cache_key, json.dumps({"date":timezone.now(), "data":context}, cls=DjangoJSONEncoder),43200)
        if only_context:
            return {"date":timezone.now(), "data":context}

        return members, mains, orphans, unregistered, total_mains, total_unreg, total_members, auth_percent, alt_ratio, service_percent, tracking, services

    def get_stats(self):
        """
        return all corpstats for corp

        :return:
        Mains with Alts Dict
        Members List[EveCharacter]
        Un-registered QuerySet[CorpMember]
        """

        linked_chars = EveCharacter.objects.filter(corporation_id=self.corp.corporation_id)  # get all authenticated characters in corp from auth internals
        linked_chars = linked_chars | EveCharacter.objects.filter(
            character_ownership__user__profile__main_character__corporation_id=self.corp.corporation_id)  # add all alts for characters in corp

        services = [svc.name for svc in ServicesHook.get_services()] # services list

        linked_chars = linked_chars.select_related('character_ownership',
                                                    'character_ownership__user__profile__main_character') \
            .prefetch_related('character_ownership__user__character_ownerships') \
        
        skiped_services = []
        for service in services:
            if service in SERVICE_DB:
                linked_chars = linked_chars.select_related("character_ownership__user__{}".format(SERVICE_DB[service]))
            else:
                skiped_services.append(service)
                logger.error(f"Unknown Service {service} Skipping")

        for service in skiped_services:
            services.remove(service)

        linked_chars = linked_chars.order_by('character_name')  # order by name

        members = [] # member list
        orphans = [] # orphan list
        alt_count = 0 # 
        services_count = {} # for the stats
        for service in services:
            services_count[service] = 0 # prefill

        mains = {} # main list
        temp_ids = [] # filter out linked vs unreg'd
        for char in linked_chars:
            try:
                main = char.character_ownership.user.profile.main_character # main from profile
                if main is not None: 
                    if main.corporation_id == self.corp.corporation_id: # iis this char in corp
                        if main.character_id not in mains: # add array
                            mains[main.character_id] = {
                                'main':main,
                                'alts':[], 
                                'services':{}
                                }
                            for service in services:
                                mains[main.character_id]['services'][service] = False # pre fill

                        if char.character_id == main.character_id:
                            for service in services:
                                try:
                                    if hasattr(char.character_ownership.user, SERVICE_DB[service]):
                                        mains[main.character_id]['services'][service] = True

corpstats/templates/corpstat/alliancestats.html
{% extends 'corpstat/base.html' %}
{% load i18n %}
{% load humanize %}
{% load corp_tags %}
{% block member_data %}
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Corporation Stats
                    </div>
                    <div class="panel-body">
                            <div class="tab-pane fade in active" id="mains">
                                    <div class="table-responsive">
                                        <table class="table table-hover" id="table-mains">
                                            <thead>
                                                <tr>
                                                    <th>Corporation</th>
                                                    <th>Members</th>
                                                    <th>Mains</th>
                                                    <th>Ratio</th>
                                                    <th>Auth'd</th>
                                                    <th>Orphans</th>
                                                    {% for corp in stats %}
                                                    {% if forloop.first %}
                                                    {% for k, v in corp.data.service_percent.items %}
                                                    <th>{{ k|title }}</th>
                                                    {% endfor %}
                                                    {% endif %}
                                                    {% endfor %}
                                                    <th>Last Update</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for corp in stats %}
                                                    <tr>
                                                        <td class="text-center" style="vertical-align:middle">{{corp.data.corp_name}}</td>
                                                        <td class="text-center" style="vertical-align:middle">{{corp.data.total_members}}</td>
                                                        <td class="text-center" style="vertical-align:middle">{{corp.data.total_mains}}</td>
                                                        <td class="text-center" style="vertical-align:middle">{{corp.data.alt_ratio|floatformat:2|intcomma}}</td>
                                                        <td class="text-center" style="color: white;background-color: {% if corp.data.auth_percent >= 95 %}#00AA33{% elif corp.data.auth_percent >= 80 %}#FF9000{% else %}#AA0000{% endif %}; vertical-align:middle">{{corp.data.auth_percent|floatformat:0|intcomma}}% ({{ corp.data.authd_members }}/{{ corp.data.total_members }})</td>
                                                        <td class="text-center" style="color: white;background-color: {% if corp.data.orphan_count == 0 %}#00AA33{% else %}#AA0000{% endif %}";vertical-align:middle">{{corp.data.orphan_count}}</td>
                                                        {% for k, v in corp.data.service_percent.items %}<td class="text-center" style="color: white;background-color: {% if v.percent >= 95 %}#00AA33{% elif v.percent >= 80 %}#FF9000{% else %}#AA0000{% endif %}">{{v.percent|floatformat:0|intcomma}}% ({{v.cnt}}/{{ corp.data.total_mains }})</td>{% endfor%}
                                                        <td class="text-center" style="vertical-align:middle">{{corp.date|str2date|naturaltime}}</td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}

{% endblock %}
{% block extra_css %}
    <style>
        .form-control {
            margin: 2px;
        }
    </style>
    {% include 'bundles/datatables-css.html' %}
{% endblock %}
{% block extra_script %}
    $(document).ready(function(){
        $('#table-mains').DataTable({
            "lengthMenu": [[-1, 25, 50], ["All", 25, 50]],

        });
    });


{% endblock %}

corpstats/templates/corpstat/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{% trans "Corporation Member Data" %}{% endblock %}
{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Corporation Member Data" %}</h1>
        <div class="col-lg-10 col-lg-offset-1 container">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <ul class="nav navbar-nav">
                        {% if available %}
                            <li class="dropdown">
                                <a href="#" id="dLabel" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="false" aria-expanded="false">{% trans "Corporations" %}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                                    {% for corpstat in available %}
                                        <li>
                                            <a href="{% url 'corpstat:view_corp' corpstat.corp.corporation_id %}">{{ corpstat.corp.corporation_name }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endif %}
                        {% if available.count > 1 %}
                            <li>
                                <a href="{% url 'corpstat:view_all' %}">{% trans "View All" %}</a>
                            </li>
                        {% endif %}
                        {% if perms.corpstats.add_corpstat %}
                            <li>
                                <a href="{% url 'corpstat:add' %}">{% trans "Add" %}</a>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="navbar-form navbar-right" role="search" action="{% url 'corpstat:search' %}" method="GET">
                        <div class="form-group">
                            <input type="text" class="form-control" name="search_string" placeholder="{% if search_string %}{{ search_string }}{% else %}{% trans "Search all corporations..." %}{% endif %}">
                        </div>
                    </form>
                </div>
            </nav>
            {% block member_data %}{% endblock %}
        </div>
    </div>
{% endblock %}

corpstats/templates/corpstat/search.html
{% extends "corpstat/base.html" %}
{% load i18n %}
{% block member_data %}
    <div class="panel panel-default">
        <div class="panel-heading clearfix">
            <div class="panel-title pull-left">{% trans "Search Results" %}</div>
        </div>
        <div class="panel-body">
            <table class="table table-hover" id="table-search">
                <thead>
                    <tr>
                        <th class="text-center"></th>
                        <th class="text-center">{% trans "Character" %}</th>
                        <th class="text-center">{% trans "Corporation" %}</th>
                        <th class="text-center">{% trans "zKillboard" %}</th>
                        <th class="text-center">{% trans "Main Character" %}</th>
                        <th class="text-center">{% trans "Main Corporation" %}</th>
                        <th class="text-center">{% trans "Main Alliance" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for result in results %}
                        <tr {% if not result.1.registered %}class="danger"{% endif %}>
                            <td class="text-center"><img src="{{ result.1.portrait_url }}" class="img-circle"></td>
                            <td class="text-center">{{ result.1.character_name }}</td>
                            <td class="text-center">{{ result.0.corp.corporation_name }}</td>
                            <td class="text-center"><a href="https://zkillboard.com/character/{{ result.1.character_id }}/" class="label label-danger" target="_blank">{% trans "Killboard" %}</a></td>
                            <td class="text-center">{{ result.1.main_character.character_name }}</td>
                            <td class="text-center">{{ result.1.main_character.corporation_name }}</td>
                            <td class="text-center">{{ result.1.main_character.alliance_name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
{% endblock %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
{% endblock %}
{% block extra_script %}
    $(document).ready(function(){
        $('#table-search').DataTable();
    });
{% endblock %}